import { useState, useCallback, useEffect } from 'react';
import type { BenchmarkConfig, BenchmarkRun, ProtocolMetrics,ProtocolType } from './types/benchmark';
import { runFullBenchmark, checkServersOnline } from './engine/benchmark';
import { ConfigPanel }    from './components/ConfigPanel';
import { MetricsPanel }   from './components/MetricsPanel';
import { ResultsTable }   from './components/ResultsTable';
import { SummaryCards }   from './components/SummaryCards';
import { ProtocolCards }  from './components/ProtocolCards';
import { ProgressBar }    from './components/ProgressBar';
import { HistoryPanel }   from './components/HistoryPanel';

// ── Inline Report Viewer ──────────────────────────────────────────────────────
function ReportViewer() {
  return (
    <div className="bg-gray-900 rounded-2xl border border-gray-800 overflow-hidden">
      <div className="p-4 border-b border-gray-800 flex items-center justify-between">
        <div>
          <h3 className="text-base font-semibold text-white">📄 HTML Report</h3>
          <p className="text-[10px] text-gray-500 mt-0.5">Generated by api-benchmark • REST vs GraphQL vs gRPC</p>
        </div>
        <a href="/public/benchmark/report.html" target="_blank" rel="noopener noreferrer"
          className="px-3 py-1.5 rounded-lg text-xs font-medium bg-blue-600 hover:bg-blue-500 text-white transition-colors">
          ↗ Open full report
        </a>
      </div>
      <div className="relative" style={{ height: '700px' }}>
        <iframe src="/public/benchmark/report.html" className="w-full h-full border-0"
          title="Benchmark Report" sandbox="allow-scripts allow-same-origin" />
      </div>
    </div>
  );
}

// ── Server Status Panel ───────────────────────────────────────────────────────
function ServerStatusPanel({
  status, checking, onRefresh,
}: {
  status: Record<'REST'|'GraphQL'|'gRPC'|'SOAP'|'Benchmark', boolean> | null;
  checking: boolean;
  onRefresh: () => void;
}) {
  const servers = [
    { name: 'REST',    port: 3001, icon: '🌐' },
    { name: 'GraphQL', port: 3002, icon: '◈'  },
    { name: 'gRPC',    port: 3003, icon: '⚡', httpPort: 3004 },
    { name: 'SOAP',    port: 3006, icon: '📦' },
    { name: 'Benchmark', port: 3005, icon: '🔬' },
  ] as const;

  const allOnline = status && servers.every(s => status[s.name as keyof typeof status]);

  return (
    <div className="bg-gray-900 rounded-2xl border border-gray-800 p-4">
      <div className="flex items-center justify-between mb-3">
        <div>
          <h3 className="text-sm font-semibold text-white">🖥️ Backend Servers</h3>
          <p className="text-[10px] text-gray-500">Chiamate HTTP reali a Node.js</p>
        </div>
        <button onClick={onRefresh} disabled={checking}
          className="text-[10px] text-gray-500 hover:text-gray-300 transition px-2 py-1 rounded bg-gray-800 border border-gray-700/50 disabled:opacity-50">
          {checking ? '⏳' : '↺ Check'}
        </button>
      </div>
      <div className="space-y-1.5">
        {servers.map(s => {
          const online = status?.[s.name];
          return (
            <div key={s.name} className="flex items-center justify-between px-3 py-2 rounded-lg bg-gray-800/50 border border-gray-700/30">
              <div className="flex items-center gap-2">
                <span className="text-sm">{s.icon}</span>
                <span className="text-xs text-gray-300 font-medium">{s.name}</span>
                <span className="text-[10px] text-gray-600">:{s.port}{('httpPort' in s) ? ` / HTTP:${s.httpPort}` : ''}</span>
              </div>
              {checking || status === null
                ? <span className="text-[10px] text-gray-600">…</span>
                : online
                  ? <span className="text-[10px] font-medium text-green-400 flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-green-400 inline-block" /> online</span>
                  : <span className="text-[10px] font-medium text-red-400 flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-red-400 inline-block" /> offline</span>
              }
            </div>
          );
        })}
      </div>
      {status && !allOnline && (
        <div className="mt-3 p-2.5 rounded-lg bg-yellow-500/5 border border-yellow-500/20">
          <p className="text-[10px] text-yellow-400 font-medium mb-1">⚠️ Server non raggiungibili</p>
          <code className="text-[10px] text-gray-400 block">npm run start:servers</code>
        </div>
      )}
      {status && allOnline && (
        <div className="mt-3 p-2 rounded-lg bg-green-500/5 border border-green-500/20">
          <p className="text-[10px] text-green-400">✓ Tutti i server online — pronto per il benchmark</p>
        </div>
      )}
    </div>
  );
}

type TabType = 'metrics' | 'table' | 'protocols' | 'report';

export function App() {
  const [isRunning,         setIsRunning]         = useState(false);
  const [progress,          setProgress]          = useState(0);
  const [currentProtocol,   setCurrentProtocol]   = useState<ProtocolType | null>(null);
  const [protocolProgress,  setProtocolProgress]  = useState(0);
  const [currentResults,    setCurrentResults]    = useState<ProtocolMetrics[]>([]);
  const [history,           setHistory]           = useState<BenchmarkRun[]>([]);
  const [selectedRunId,     setSelectedRunId]     = useState<string | null>(null);
  const [activeTab,         setActiveTab]         = useState<TabType>('metrics');
  const [serverStatus,      setServerStatus]      = useState<Record<'REST'|'GraphQL'|'gRPC'|'SOAP'|'Benchmark', boolean> | null>(null);
  const [checkingServers,   setCheckingServers]   = useState(true);

  const refreshServerStatus = useCallback(async () => {
    setCheckingServers(true);
    const status = await checkServersOnline();
    setServerStatus(status);
    setCheckingServers(false);
  }, []);

  useEffect(() => { refreshServerStatus(); }, [refreshServerStatus]);

  const handleRun = useCallback(async (config: BenchmarkConfig) => {
    setIsRunning(true);
    setProgress(0);
    setCurrentResults([]);
    setActiveTab('metrics');
    const startTime = performance.now();
    try {
      const results = await runFullBenchmark(config, (overall, proto, protoPct, partial) => {
        setProgress(overall);
        setCurrentProtocol(proto);
        setProtocolProgress(protoPct);
        setCurrentResults([...partial]);
      });
      const run: BenchmarkRun = {
        id: crypto.randomUUID(), timestamp: Date.now(), config, results,
        status: 'completed', durationMs: performance.now() - startTime,
      };
      setHistory(prev => [run, ...prev]);
      setSelectedRunId(run.id);
      setCurrentResults(results);
    } catch (err) {
      console.error('Benchmark failed:', err);
    } finally {
      setIsRunning(false);
      setProgress(100);
      setCurrentProtocol(null);
    }
  }, []);

  const handleSelectRun = useCallback((run: BenchmarkRun) => {
    setSelectedRunId(run.id);
    setCurrentResults(run.results);
  }, []);

  const hasResults = currentResults.length > 0;

  const tabs: { id: TabType; label: string; icon: string }[] = [
    { id: 'metrics',   label: 'Metrics',        icon: '📊' },
    { id: 'table',     label: 'Data Table',      icon: '📋' },
    { id: 'protocols', label: 'Protocol Guide',  icon: '📚' },
    { id: 'report',    label: 'HTML Report',     icon: '📄' },
  ];

  const showTabs = hasResults || activeTab === 'protocols' || activeTab === 'report';

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <header className="border-b border-gray-800 bg-gray-950/90 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center text-base shadow-lg shadow-blue-500/20">⚡</div>
              <div>
                <h1 className="text-base font-bold bg-gradient-to-r from-blue-400 to-cyan-300 bg-clip-text text-transparent">API Protocol Benchmark</h1>
                <p className="text-[10px] text-gray-500">Fetch HTTP reale → Node.js servers · REST · GraphQL · gRPC · SOAP · Memoria · CPU</p>
              </div>
            </div>
            <div className="hidden sm:flex items-center gap-1.5 text-[10px] text-gray-500">
              <span className="px-2 py-1 rounded bg-gray-800/80 border border-gray-700/50">fetch() HTTP</span>
              <span className="px-2 py-1 rounded bg-gray-800/80 border border-gray-700/50">performance.now()</span>
              <span className="px-2 py-1 rounded bg-gray-800/80 border border-gray-700/50">/metrics real</span>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-5">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">

          {/* ── Sidebar ── */}
          <div className="lg:col-span-4 xl:col-span-3 space-y-4">
            <ServerStatusPanel status={serverStatus} checking={checkingServers} onRefresh={refreshServerStatus} />
            <ConfigPanel onRun={handleRun} isRunning={isRunning} />
            <HistoryPanel history={history} onSelect={handleSelectRun} selectedId={selectedRunId}
              onClear={() => { setHistory([]); setSelectedRunId(null); }} />
          </div>

          {/* ── Main content ── */}
          <div className="lg:col-span-8 xl:col-span-9 space-y-4">

            {isRunning && (
              <ProgressBar progress={progress} currentProtocol={currentProtocol} protocolProgress={protocolProgress} />
            )}

            {hasResults && !isRunning && <SummaryCards results={currentResults} />}

            {/* Tab bar */}
            {showTabs && (
              <div className="flex gap-0.5 bg-gray-900 rounded-xl p-0.5 border border-gray-800 overflow-x-auto">
                {tabs.map(tab => (
                  <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                    className={`flex-1 min-w-fit py-2 px-3 rounded-lg text-xs font-medium transition-all whitespace-nowrap
                      ${activeTab === tab.id
                        ? 'bg-gray-800 text-white shadow'
                        : 'text-gray-500 hover:text-gray-400 hover:bg-gray-800/30'}`}>
                    <span className="hidden sm:inline">{tab.icon} </span>{tab.label}
                  </button>
                ))}
              </div>
            )}

            {/* Tab content */}
            {activeTab === 'metrics'   && hasResults && <MetricsPanel  results={currentResults} />}
            {activeTab === 'table'     && hasResults && <ResultsTable  results={currentResults} />}
            {activeTab === 'protocols' &&               <ProtocolCards />}
            {activeTab === 'report'    &&               <ReportViewer />}

            {/* Empty state */}
            {!hasResults && !isRunning && activeTab === 'metrics' && (
              <div className="bg-gray-900 rounded-2xl border border-gray-800 p-10 text-center">
                <div className="text-5xl mb-3">🔬</div>
                <h3 className="text-lg font-bold text-white mb-1">Nessun dato</h3>
                <p className="text-sm text-gray-400 max-w-lg mx-auto mb-5">
                  Configura i parametri e avvia il benchmark. REST, GraphQL, gRPC e SOAP girano su server{' '}
                  <strong>Node.js reali</strong> — latenza e throughput misurati con{' '}
                  <code className="text-blue-400 text-xs bg-gray-800 px-1 py-0.5 rounded">performance.now()</code>,
                  memoria e CPU campionati in tempo reale da{' '}
                  <code className="text-blue-400 text-xs bg-gray-800 px-1 py-0.5 rounded">/metrics</code>.
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 max-w-md mx-auto mb-4">
                  {[
                    { n: 'REST',    d: 'JSON + HTTP routing (port 3001)',        i: '🌐' },
                    { n: 'GraphQL', d: 'Query parsing + resolvers (port 3002)',   i: '◈'  },
                    { n: 'gRPC',    d: 'Protobuf binary encode/decode (port 3003)', i: '⚡' },
                    { n: 'SOAP',    d: 'WSDL + XML operation dispatch (port 3006)', i: '📦' },
                  ].map(p => (
                    <div key={p.n} className="px-3 py-2 rounded-lg bg-blue-500/5 border border-blue-500/20 text-left">
                      <div className="text-xs text-white font-medium">{p.i} {p.n}</div>
                      <div className="text-[10px] text-gray-500 mt-0.5">{p.d}</div>
                    </div>
                  ))}
                </div>
                <p className="text-[11px] text-gray-600">MQTT · Webhooks sono documentati nel Protocol Guide</p>
              </div>
            )}

          </div>
        </div>
      </div>

      <footer className="border-t border-gray-800/50 mt-8 py-4">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 text-center">
          <p className="text-[10px] text-gray-600 leading-relaxed">
            <span className="text-gray-500 font-medium">Metriche reali:</span>{' '}
            Latenza (performance.now()), Throughput (req/s), Memoria heap (MB) e CPU % da /metrics.{' '}
            <span className="text-gray-700">Info-only:</span>{' '}
            MQTT · Webhooks — documentati nel Protocol Guide.
          </p>
        </div>
      </footer>
    </div>
  );
}
